### ISSUE TITLE
yfinance error——AttributeError: 'Index' object has no attribute 'tzinfo'

### ISSUE THREAD

**Issue by Buen16** [kieran-mackle/autotrader-demo#15]
```
1 Failed download:
- ETH-USD: No data found for this date range, symbol may be delisted
Traceback (most recent call last):
  File "D:\my ebooks\autotrader-demo-main\runfile.py", line 26, in <module>
    at.run()
  File "D:\Program Files\anaconda3\envs\atdemo\lib\site-packages\autotrader\autotrader.py", line 1142, in run
    self._main()
  File "D:\Program Files\anaconda3\envs\atdemo\lib\site-packages\autotrader\autotrader.py", line 1613, in _main
    bot = AutoTraderBot(
  File "D:\Program Files\anaconda3\envs\atdemo\lib\site-packages\autotrader\autobot.py", line 223, in __init__
    self._refresh_data(deploy_dt)
  File "D:\Program Files\anaconda3\envs\atdemo\lib\site-packages\autotrader\autobot.py", line 449, in _refresh_data
    data, multi_data, quote_data, auxdata = self.Stream.refresh(timestamp=timestamp)
  File "D:\Program Files\anaconda3\envs\atdemo\lib\site-packages\autotrader\utilities.py", line 1174, in refresh
    data = data_func(
  File "D:\Program Files\anaconda3\envs\atdemo\lib\site-packages\autotrader\autodata.py", line 783, in _yahoo
    if data.index.tzinfo is None:
AttributeError: 'Index' object has no attribute 'tzinfo'
```
I have tried every solution， but they didn't work. I have tried many versions of yfiance and pandas, but this problem still exist

**Comment by Auditor1234** [comment]
Have you ever solved this problem yet? I also encountered this.

**Comment by Auditor1234** [comment]
I think I have got the answer. This problem occurs when your country or region is not supported by yahoo finance website. So you only need to change your IP location, just use VPN to change your IP, that is it.
