### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'lower' in FINTA

### ISSUE THREAD

**Issue by YonasJ** [kieran-mackle/autotrader-demo#23]
**Describe the bug**

Check out demo reposity, and run it.

I get the exception below.

AttributeError: 'tuple' object has no attribute 'lower'

**To Reproduce**
python run.py

**Screenshots**
Traceback (most recent call last):
  File "C:\Users\yonas\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yonas\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\yonas\.vscode\extensions\ms-python.debugpy-2024.14.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 71, in <module>
    cli.main()
  File "c:\Users\yonas\.vscode\extensions\ms-python.debugpy-2024.14.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 
501, in main
    run()
  File "c:\Users\yonas\.vscode\extensions\ms-python.debugpy-2024.14.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 
351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\yonas\.vscode\extensions\ms-python.debugpy-2024.14.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 310, in run_path      
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\yonas\.vscode\extensions\ms-python.debugpy-2024.14.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)  File "c:\Users\yonas\.vscode\extensions\ms-python.debugpy-2024.14.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 118, in _run_code     
    exec(code, run_globals)
  File "C:\Users\yonas\Documents\autotrader-demo\run.py", line 14, in <module>
    at.run()
  File "c:\Users\yonas\Documents\autotrader-demo\.venv\Lib\site-packages\autotrader\autotrader.py", line 1109, in run
    self._main()
  File "c:\Users\yonas\Documents\autotrader-demo\.venv\Lib\site-packages\autotrader\autotrader.py", line 1468, in _main
    bot = AutoTraderBot(
          ^^^^^^^^^^^^^^
  File "c:\Users\yonas\Documents\autotrader-demo\.venv\Lib\site-packages\autotrader\autobot.py", line 203, in __init__
    my_strat.create_plotting_indicators(data)
  File "C:\Users\yonas\Documents\autotrader-demo\strategies\long_ema_crossover.py", line 
29, in create_plotting_indicators
    slow_ema = TA.EMA(data, self.params["slow_ema"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  **File "c:\Users\yonas\Documents\autotrader-demo\.venv\Lib\site-packages\finta\finta.py", line 15, in wrap
    args[i] = args[i].rename(columns={c: c.lower() for c in args[i].columns})**
                                         ^^^^^^^
**AttributeError: 'tuple' object has no attribute 'lower'**

**Comment by vtexier** [comment]
Fixed in `autotrader-demo/strategies/macd.py` with :
```python

    def generate_features(self, data: pd.DataFrame):
        # fix Finta multi-column bug
        data.columns = data.columns.get_level_values(0)
```
